if(NOT DEFINED IPGEOLOCATION_TEST_BINARY OR IPGEOLOCATION_TEST_BINARY STREQUAL "")
    message(FATAL_ERROR "IPGEOLOCATION_TEST_BINARY is required")
endif()
if(NOT DEFINED IPGEOLOCATION_PROFILE_RAW OR IPGEOLOCATION_PROFILE_RAW STREQUAL "")
    message(FATAL_ERROR "IPGEOLOCATION_PROFILE_RAW is required")
endif()
if(NOT DEFINED IPGEOLOCATION_PROFILE_DATA OR IPGEOLOCATION_PROFILE_DATA STREQUAL "")
    message(FATAL_ERROR "IPGEOLOCATION_PROFILE_DATA is required")
endif()
if(NOT DEFINED IPGEOLOCATION_REPORT_FILE OR IPGEOLOCATION_REPORT_FILE STREQUAL "")
    message(FATAL_ERROR "IPGEOLOCATION_REPORT_FILE is required")
endif()
if(NOT DEFINED IPGEOLOCATION_MIN_LINE OR IPGEOLOCATION_MIN_LINE STREQUAL "")
    message(FATAL_ERROR "IPGEOLOCATION_MIN_LINE is required")
endif()
if(NOT DEFINED IPGEOLOCATION_MIN_BRANCH OR IPGEOLOCATION_MIN_BRANCH STREQUAL "")
    message(FATAL_ERROR "IPGEOLOCATION_MIN_BRANCH is required")
endif()
if(NOT DEFINED IPGEOLOCATION_MIN_FUNCTION OR IPGEOLOCATION_MIN_FUNCTION STREQUAL "")
    message(FATAL_ERROR "IPGEOLOCATION_MIN_FUNCTION is required")
endif()

get_filename_component(IPGEOLOCATION_COVERAGE_DIR "${IPGEOLOCATION_PROFILE_RAW}" DIRECTORY)
file(MAKE_DIRECTORY "${IPGEOLOCATION_COVERAGE_DIR}")
file(REMOVE "${IPGEOLOCATION_PROFILE_RAW}" "${IPGEOLOCATION_PROFILE_DATA}" "${IPGEOLOCATION_REPORT_FILE}")

if(DEFINED IPGEOLOCATION_XCRUN_EXECUTABLE AND NOT IPGEOLOCATION_XCRUN_EXECUTABLE STREQUAL "")
    set(IPGEOLOCATION_LLVM_PROFDATA_COMMAND "${IPGEOLOCATION_XCRUN_EXECUTABLE}" llvm-profdata)
    set(IPGEOLOCATION_LLVM_COV_COMMAND "${IPGEOLOCATION_XCRUN_EXECUTABLE}" llvm-cov)
else()
    if(NOT DEFINED IPGEOLOCATION_LLVM_PROFDATA_EXECUTABLE OR IPGEOLOCATION_LLVM_PROFDATA_EXECUTABLE STREQUAL "")
        message(FATAL_ERROR "IPGEOLOCATION_LLVM_PROFDATA_EXECUTABLE is required when xcrun is unavailable")
    endif()
    if(NOT DEFINED IPGEOLOCATION_LLVM_COV_EXECUTABLE OR IPGEOLOCATION_LLVM_COV_EXECUTABLE STREQUAL "")
        message(FATAL_ERROR "IPGEOLOCATION_LLVM_COV_EXECUTABLE is required when xcrun is unavailable")
    endif()
    set(IPGEOLOCATION_LLVM_PROFDATA_COMMAND "${IPGEOLOCATION_LLVM_PROFDATA_EXECUTABLE}")
    set(IPGEOLOCATION_LLVM_COV_COMMAND "${IPGEOLOCATION_LLVM_COV_EXECUTABLE}")
endif()

execute_process(
    COMMAND "${CMAKE_COMMAND}" -E env "LLVM_PROFILE_FILE=${IPGEOLOCATION_PROFILE_RAW}" "${IPGEOLOCATION_TEST_BINARY}"
    RESULT_VARIABLE IPGEOLOCATION_TEST_RESULT
    OUTPUT_VARIABLE IPGEOLOCATION_TEST_STDOUT
    ERROR_VARIABLE IPGEOLOCATION_TEST_STDERR
)
if(NOT IPGEOLOCATION_TEST_RESULT EQUAL 0)
    message(FATAL_ERROR
        "Coverage gate could not run the unit test binary.\n"
        "stdout:\n${IPGEOLOCATION_TEST_STDOUT}\n"
        "stderr:\n${IPGEOLOCATION_TEST_STDERR}")
endif()

execute_process(
    COMMAND ${IPGEOLOCATION_LLVM_PROFDATA_COMMAND} merge -sparse "${IPGEOLOCATION_PROFILE_RAW}" -o "${IPGEOLOCATION_PROFILE_DATA}"
    RESULT_VARIABLE IPGEOLOCATION_PROFDATA_RESULT
    OUTPUT_VARIABLE IPGEOLOCATION_PROFDATA_STDOUT
    ERROR_VARIABLE IPGEOLOCATION_PROFDATA_STDERR
)
if(NOT IPGEOLOCATION_PROFDATA_RESULT EQUAL 0)
    message(FATAL_ERROR
        "Coverage gate could not merge the LLVM profile.\n"
        "stdout:\n${IPGEOLOCATION_PROFDATA_STDOUT}\n"
        "stderr:\n${IPGEOLOCATION_PROFDATA_STDERR}")
endif()

execute_process(
    COMMAND ${IPGEOLOCATION_LLVM_COV_COMMAND}
        report
        "${IPGEOLOCATION_TEST_BINARY}"
        "-instr-profile=${IPGEOLOCATION_PROFILE_DATA}"
        --show-branch-summary
        "--ignore-filename-regex=${IPGEOLOCATION_IGNORE_FILENAME_REGEX}"
    RESULT_VARIABLE IPGEOLOCATION_COVERAGE_RESULT
    OUTPUT_VARIABLE IPGEOLOCATION_COVERAGE_REPORT
    ERROR_VARIABLE IPGEOLOCATION_COVERAGE_STDERR
)
if(NOT IPGEOLOCATION_COVERAGE_RESULT EQUAL 0)
    message(FATAL_ERROR
        "Coverage gate could not generate the llvm-cov report.\n"
        "stdout:\n${IPGEOLOCATION_COVERAGE_REPORT}\n"
        "stderr:\n${IPGEOLOCATION_COVERAGE_STDERR}")
endif()

file(WRITE "${IPGEOLOCATION_REPORT_FILE}" "${IPGEOLOCATION_COVERAGE_REPORT}")

string(REGEX MATCH "TOTAL[^\n\r]*" IPGEOLOCATION_TOTAL_LINE "${IPGEOLOCATION_COVERAGE_REPORT}")
if(IPGEOLOCATION_TOTAL_LINE STREQUAL "")
    message(FATAL_ERROR
        "Coverage gate could not locate the TOTAL row in the llvm-cov report.\n"
        "${IPGEOLOCATION_COVERAGE_REPORT}")
endif()

string(REGEX REPLACE
    ".*TOTAL[ \t]+[0-9]+[ \t]+[0-9]+[ \t]+([0-9.]+)%[ \t]+[0-9]+[ \t]+[0-9]+[ \t]+([0-9.]+)%[ \t]+[0-9]+[ \t]+[0-9]+[ \t]+([0-9.]+)%[ \t]+[0-9]+[ \t]+[0-9]+[ \t]+([0-9.]+)%.*"
    "\\1;\\2;\\3;\\4"
    IPGEOLOCATION_TOTAL_VALUES
    "${IPGEOLOCATION_TOTAL_LINE}"
)

list(LENGTH IPGEOLOCATION_TOTAL_VALUES IPGEOLOCATION_TOTAL_VALUES_LENGTH)
if(NOT IPGEOLOCATION_TOTAL_VALUES_LENGTH EQUAL 4)
    message(FATAL_ERROR
        "Coverage gate could not parse the TOTAL row.\n"
        "TOTAL row: ${IPGEOLOCATION_TOTAL_LINE}")
endif()

list(GET IPGEOLOCATION_TOTAL_VALUES 1 IPGEOLOCATION_FUNCTION_COVERAGE)
list(GET IPGEOLOCATION_TOTAL_VALUES 2 IPGEOLOCATION_LINE_COVERAGE)
list(GET IPGEOLOCATION_TOTAL_VALUES 3 IPGEOLOCATION_BRANCH_COVERAGE)

message(STATUS
    "IPGeolocation C++ unit coverage: "
    "line=${IPGEOLOCATION_LINE_COVERAGE}% "
    "branch=${IPGEOLOCATION_BRANCH_COVERAGE}% "
    "function=${IPGEOLOCATION_FUNCTION_COVERAGE}%")

set(IPGEOLOCATION_COVERAGE_FAILURES "")
if(IPGEOLOCATION_LINE_COVERAGE LESS IPGEOLOCATION_MIN_LINE)
    string(APPEND IPGEOLOCATION_COVERAGE_FAILURES
        "line coverage ${IPGEOLOCATION_LINE_COVERAGE}% is below ${IPGEOLOCATION_MIN_LINE}%\n")
endif()
if(IPGEOLOCATION_BRANCH_COVERAGE LESS IPGEOLOCATION_MIN_BRANCH)
    string(APPEND IPGEOLOCATION_COVERAGE_FAILURES
        "branch coverage ${IPGEOLOCATION_BRANCH_COVERAGE}% is below ${IPGEOLOCATION_MIN_BRANCH}%\n")
endif()
if(IPGEOLOCATION_FUNCTION_COVERAGE LESS IPGEOLOCATION_MIN_FUNCTION)
    string(APPEND IPGEOLOCATION_COVERAGE_FAILURES
        "function coverage ${IPGEOLOCATION_FUNCTION_COVERAGE}% is below ${IPGEOLOCATION_MIN_FUNCTION}%\n")
endif()

if(NOT IPGEOLOCATION_COVERAGE_FAILURES STREQUAL "")
    message(FATAL_ERROR
        "Coverage thresholds were not met:\n"
        "${IPGEOLOCATION_COVERAGE_FAILURES}\n"
        "Full report:\n${IPGEOLOCATION_COVERAGE_REPORT}")
endif()
